name: Support Request
description: File a support request
title: "[support] <title>"
labels: [needs triage, medium, wormhole-support]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  attributes:
    label: have you checked our wiki for common solutions?
    description: Please take a look to our [wiki page](../wiki) or [docs](https://portalbridge.com/docs) to see if we already have a **how to** to help you.
    options:
    - label: I have searched the wiki or docs
      required: true
- type: dropdown
  attributes:
    label: Bridge Experience
    description: Which bridging experience did you use?
    options:
      - https://portalbridge.com
      - https://portalbridge.com/advanced-tools
      - https://portalbridge.com/usdc-bridge
      - other
  validations:
    required: true
- type: input
  attributes:
    label: Bridge Experience URL
    description: What is the URL of the other bridging experience you used?
    placeholder: ex. https://hub.injective.network/bridge/
  validations:
    required: false
- type: textarea
  attributes:
    label: Operation Details
    description: |
      examples:
        - **Source Chain**: Ethereum
        - **Source Chain Wallet**: Metamask
        - **Target Chain**: Solana
        - **Target Chain Wallet**: Phantom
        - **Asset Type**: NFT | Token
        - **Tx**: https://etherscan.io/tx/0x1adcb5e9d189c8ec89c7fcfa43987847f035ca31cc5462def41682ccaa200fc1
    value: |
        - Source Chain:
        - Source Chain Wallet:
        - Target Chain:
        - Target Chain Wallet:
        - Asset Type:
        - Tx:
    render: markdown
  validations:
    required: false
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. At www.portalbridge.com/#/transfer ...
      2. With Ethereum as source chain and Metamask wallet connected...
      3. When I try to select my token at the token picker it does not appear
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
