| Token (origin) | Token (target)           | Markets                                                                                                                                                                                      | Contract address                             |
| -------------- | ------------------------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------- |
| USDC           | USDCet (Wormhole)        | [Saber](https://app.saber.so), [Mercurial](https://mercurial.finance/), [Jupiter](https://jup.ag/)                                                                                           | A9mUU4qviSctJVPJdBJWkb28deg915LYJKrzQ19ji3FM |
| USDT           | USDTet (Wormhole)        | [Saber](https://app.saber.so), [Mercurial](https://mercurial.finance/), [Jupiter](https://jup.ag/)                                                                                           | Dn4noZ5jgGfkntzcQSUZ8czkreiZ1ForXYoV2H8Dm7S1 |
| ETH/WETH       | Ether(Wormhole)          | [Orca](https://www.orca.so/), [Saber](https://app.saber.so), [Tulip](https://tulip.garden/), [Port](https://mainnet.port.finance/#/markets), [Francium](https://francium.io/app/invest/farm) | 7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs |
| DAI            | DAI(Wormhole)            | [Saber](https://app.saber.so), [Mercurial](https://mercurial.finance/), [Jupiter](https://jup.ag/)                                                                                           | EjmyN6qEC1Tf1JxiG1ae7UTJhUxSwk1TCWNWqxWV4J6o |
| wBTC           | wBTC(Wormhole)           | [Raydium](https://raydium.io/swap/), [Orca](https://www.orca.so/)                                                                                                                            | 3NZ9JMVBmGAqocybic2c7LQCJScmgsAZ6vQqTDzcqmJh |
| USDK           | USDK(Wormhole)           | [Saber](https://app.saber.so)                                                                                                                                                                | 43m2ewFV5nDepieFjT9EmAQnc1HRtAF247RBpLGFem5F |
| FRAX           | Frax(Wormhole)           | [Saber](https://app.saber.so)                                                                                                                                                                | FR87nWEUxVgerFGhZM8Y4AggKGLnaXswr1Pd8wZ4kZcp |
| SHIB           | SHIBA INU(Wormhole)      | [Raydium](https://raydium.io/swap/)                                                                                                                                                          | CiKu4eHsVrc1eueVQeHn7qhXTcVu95gSQmBpX4utjL9z |
| SUSHI          | SushiToken (Wormhole)    | [Raydium](https://raydium.io/swap/)                                                                                                                                                          | ChVzxWRmrTeSgwd3Ui3UumcN8KX7VK3WaD4KGeSKpypj |
| DYDX           | DYDX (Wormhole)          | [Raydium](https://raydium.io/swap/)                                                                                                                                                          | 4Hx6Bj56eGyw8EJrrheM6LBQAvVYRikYCWsALeTrwyRU |
| MANA           | MANA(Wormhole)           | [Raydium](https://raydium.io/swap/)                                                                                                                                                          | 7dgHoN8wBZCc5wbnQ2C47TDnBMAxG4Q5L3KjP67z8kNi |
| SAND           | The Sandbox(Wormhole)    | [Raydium](https://raydium.io/swap/)                                                                                                                                                          | 49c7WuCZkQgc3M4qH8WuEUNXfgwupZf1xqWkDQ7gjRGt |
| UNI            | Uniswap(Wormhole)        | [Raydium](https://raydium.io/swap/)                                                                                                                                                          | 8FU95xFJhUUkyyCLU13HSzDLs7oC4QZdXQHL6SCeab36 |
| LDO            | Lido DAO Token(Wormhole) | [Jupiter](https://jup.ag/), [Orca](https://www.orca.so/)                                                                                                                                     | HZRCwxP2Vq9PCpPXooayhJ2bxTpo5xfpQrwB1svh332p |
| HXRO           | HXRO (Wormhole)          | [Raydium](https://raydium.io/swap/), [Orca](https://www.orca.so/)                                                                                                                            | HxhWkVpk5NS4Ltg5nij2G671CKXFRKPK8vy271Ub4uEK |
